chore(linear): add debug info (#8692)
RelatedTo: MRGFY-2857

Change-Id: I5edaf5ccafdeed25b9c460aea50f453b165f0a38

diff --git a/.github/workflows/create-linear-for-docs.yaml b/.github/workflows/create-linear-for-docs.yaml
--- a/.github/workflows/create-linear-for-docs.yaml
+++ b/.github/workflows/create-linear-for-docs.yaml
@@ -18,7 +18,12 @@ jobs:
         run: |
           echo "Author: ${PR_AUTHOR}"
           ASSIGNEE_EMAIL=$(echo "$EMAIL_MAPPING" | awk '/ '"${PR_AUTHOR}"'$/{print $1}')
+          if [ -z "$ASSIGNEE_EMAIL" ]; then
+            echo "Email of ${PR_AUTHOR} not found in email mapping: ${EMAIL_MAPPING}"
+            exit 1
+          fi
           echo "Author email: ${ASSIGNEE_EMAIL}"
+
 
           JSON_PAYLOAD=$(jq -n \
              --arg email "$ASSIGNEE_EMAIL" \
